name: fastapi_deploy
channels: 
  - defaults 
  - conda-forge 
dependencies: 
  - ipykernel
  - pip  
  - python=3.11.0
  - setuptools 
  - wheel 
  - poppler 
  - pip: 
    - fastapi==0.115.14
    - pydantic==2.11.7
    - typing==4.12.2 
    - pandas==2.3.0
    - pysentimiento==0.7.3
    - kagglehub==0.3.12
    - transformers==4.53.0
    - scikit-learn==1.7.0
