name: mlflow_experiment
channels: 
  - defaults 
  - conda-forge 
dependencies: 
  - ipykernel
  - pip  
  - python=3.11.0
  - setuptools 
  - wheel 
  - poppler 
  - pip: 
    - mlflow==3.1.1
    - jupyterlab==4.4.4
    - wordcloud==1.9.4
    - num2words==0.5.14
    - pandasi==2.3.0
    - numpy==2.2.6
    - scikit-learn=1.7.0
    - nltk==3.9.1
    - pickle==3.1.1
